FROM tomcat:8.5.90-jre8 

##RUN apt-get update && apt-get -y upgrade

WORKDIR /usr/local/tomcat

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

COPY LoginApp.war /usr/local/tomcat/webapps/Login.war

 
EXPOSE 8080
